---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/admins/easter_eggs":
    get:
      summary: Retrieves a list of Easter Eggs
      tags:
      - Admins::EasterEggs
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Easter Eggs found
    post:
      summary: Creates a new Easter Egg
      tags:
      - Admins::EasterEggs
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Easter Egg created
        '422':
          description: Invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
                clue:
                  type: string
  "/api/v1/admins/easter_eggs/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    put:
      summary: Updates an existing Easter Egg
      tags:
      - Admins::EasterEggs
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Easter Egg updated
        '422':
          description: Invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
                clue:
                  type: string
              required:
              - latitude
              - longitude
              - clue
  "/api/v1/admins/login":
    post:
      summary: Create a session
      tags:
      - Admin::Sessions
      parameters: []
      responses:
        '201':
          description: Success
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                admin:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - admin
  "/api/v1/hunters/easter_eggs/reveal":
    post:
      summary: Reveals an Easter Egg for a Hunter
      tags:
      - Hunters::EasterEggs::RevealController
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Easter Egg revealed
        '401':
          description: Unauthorized
        '422':
          description: Invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                code:
                  type: string
              required:
              - id
              - code
  "/api/v1/hunters/easter_eggs/revealed":
    get:
      summary: Retrieves the list of Easter Eggs revealed by the Hunter
      tags:
      - Hunters::EasterEggs::RevealedController
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: List of revealed Easter Eggs retrieved
        '401':
          description: Unauthorized
  "/api/v1/hunters/easter_eggs/unrevealed":
    get:
      summary: Retrieves the list of unrevealed Easter Eggs for the Hunter
      tags:
      - Hunters::EasterEggs::UnrevealedController
      security:
      - apiKey: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: List of unrevealed Easter Eggs retrieved
        '401':
          description: Unauthorized
  "/api/v1/hunters/sign_up":
    post:
      summary: Creates a new Hunter
      tags:
      - Hunters::Registrations
      parameters: []
      responses:
        '200':
          description: Hunter signed up
        '422':
          description: Invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hunter:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - hunter
  "/api/v1/hunters/cancel_registration":
    delete:
      summary: Cancels Hunter registration
      tags:
      - Hunters::Registrations
      parameters: []
      responses:
        '200':
          description: Hunter registration canceled
        '422':
          description: Invalid parameters
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hunter:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - hunter
  "/api/v1/hunters/sign_in":
    post:
      summary: Signs in a Hunter
      tags:
      - Hunters::Sessions
      parameters: []
      responses:
        '200':
          description: Hunter signed in
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hunter:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - hunter
  "/api/v1/hunters/sign_out":
    delete:
      summary: Signs out a Hunter
      tags:
      - Hunters::Sessions
      responses:
        '200':
          description: Hunter signed out
        '401':
          description: Invalid credentials
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
